volumes:
  postgres_data:

services:
  db:
    image: "postgres:17-alpine"
    container_name: db
    restart: always
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
     - '5432:5432'
