volumes:
  postgres_data:
  collect_media:

services:
  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - collect_media:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - db
  db:
    image: "postgres:17-alpine"
    container_name: db
    restart: always
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
     - '5432:5432'

  redis:
    image: "redis:7-alpine"
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
  
  celery:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: celery -A server worker -l info
    depends_on:
      - db
      - redis

  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - collect_media:/app/media
    depends_on:
      - db
      - redis
