# Generated by Django 5.2.6 on 2025-09-14 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Title of collect')),
                ('reason', models.CharField(choices=[('BIRTHDAY', 'birthday'), ('WEDDING', 'wedding'), ('CHARITY', 'charity')], max_length=128, verbose_name='Reason')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finished status')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finish datetime')),
                ('description', models.TextField(verbose_name='description')),
                ('target_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Target amount')),
                ('current_amount', models.PositiveIntegerField(default=0, verbose_name='Current amount')),
                ('donators_count', models.PositiveIntegerField(default=0, verbose_name='Donators count')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collect_image/', verbose_name='Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Collect',
                'verbose_name_plural': 'Collects',
                'ordering': ('title', 'target_amount', 'current_amount'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Amount of money')),
                ('comment', models.TextField(verbose_name='User`s comment')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.collect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ('amount', 'comment'),
                'default_related_name': '%(class)ss',
            },
        ),
    ]
