# Generated by Django 5.2.6 on 2025-09-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='current_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Current amount'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='donators_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Donators count'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='target_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Target amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Amount of money'),
        ),
    ]
