# Generated by Django 5.2.6 on 2025-09-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_collect_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/collect_image', verbose_name='Image'),
        ),
    ]
