# Generated by Django 5.2.6 on 2025-09-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_collect_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Finished status'),
        ),
    ]
