# Generated by Django 5.2.6 on 2025-09-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_collect_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish datetime'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collect_image/', verbose_name='Image'),
        ),
    ]
